### ISSUE TITLE
生发补全计划V1.0

### ISSUE THREAD

**Issue by Varian-liu** [JoeSai/GGJ2023_ROOTS#2]
接下来是补充以及完善目前的游戏功能

- [ ] 1.将【头皮发麻】DEBUFF效果从“一定区域无法生长头发”改为“一定区域射击上会掉头发”。显示效果从黑色变为红色
- [ ] 2.新增主角针对每句来GANK的话语进行一个内心的独白。
- [ ] 3.右下角生发数增加一个目标发量，显示本关通关所需目标数
- [ ] 4.每一局主角头上的头发不清空，保留上一关剩余头发。
- [ ] 5.开局给玩家一个基础数值的发量，例如100，随后每关的难度都以掉头发为主。
- [ ] 6.交换关底选项与商店的顺序，给予选项更多的平衡性数值，方便调整

具体的数值以及文本，我会更新在这个单子后边

**Comment by kavinrun** [comment]
我来！
